#!/bin/bash

# Download the Google Cloud SDK tarball
curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz

# Extract the tarball
tar -xzf google-cloud-cli-linux-x86_64.tar.gz

# Navigate to the extracted directory
cd google-cloud-sdk

# Run the installation script
./install.sh


# Add gcloud to PATH
echo 'export PATH=$PATH:~/google-cloud-sdk/bin' >> ~/.bashrc
source ~/.bashrc

# install cassandra using tarball
cd ~
curl -OL http://apache.mirror.digitalpacific.com.au/cassandra/4.0.0/apache-cassandra-4.0.0-bin.tar.gz


gpg --print-md SHA256 apache-cassandra-4.0.0-bin.tar.gz
curl -L https://downloads.apache.org/cassandra/4.0.0/apache-cassandra-4.0.0-bin.tar.gz.sha256


tar xzvf apache-cassandra-4.0.0-bin.tar.gz

# Navigate to the extracted directory
cd apache-cassandra-4.0.0

# Add cassandra to PATH
echo 'export PATH=$PATH:~/apache-cassandra-4.0.0/bin' >> ~/.bashrc
source ~/.bashrc

